Prevent the Ore Finder Wand from imploding
GTNewHorizons/IFU pull request #13
Opened 2023-05-12 18:12 UTC by wlhlm

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13480

2023-05-12 19:37 UTC, OneEyeMaker commented
Current code doesn't solve issue completely, because there are keyboard shortcuts which allow to move items. More proper solution would be to implement something like [locked slot](https://github.com/GTNewHorizons/ForestryMC/blob/master/src/main/java/forestry/core/gui/slots/SlotLocked.java) and adding such slot [like this](https://github.com/GTNewHorizons/ForestryMC/blob/master/src/main/java/forestry/core/gui/ContainerItemInventory.java#L33-L37).

2023-05-12 20:14 UTC, wlhlm commented
IFU already uses a custom [Slot class](https://github.com/GTNewHorizons/IFU/blob/4b89084a4e6169fe10d74982e5e6ce9e05905df1/src/main/java/com/encraft/dz/container/SlotItemInv.java). My implementation is based on the GT++ backpack. The code has a few comments [1](https://github.com/GTNewHorizons/GTplusplus/blob/aefb6dce11384bc72dd340fa0fb1037988e35916/src/main/java/gtPlusPlus/core/container/Container_BackpackBase.java#L39-L46) [2](https://github.com/GTNewHorizons/GTplusplus/blob/aefb6dce11384bc72dd340fa0fb1037988e35916/src/main/java/gtPlusPlus/core/slots/SlotItemBackpackInv.java#L15-L26) [3](https://github.com/GTNewHorizons/GTplusplus/blob/aefb6dce11384bc72dd340fa0fb1037988e35916/src/main/java/gtPlusPlus/core/container/Container_BackpackBase.java#L163) regarding backpack self-storage. Are you telling me that the GT++ backpack has issues too?

I have done some playtesting and it all worked as expected. Do you know some keybinds that might still allow transferring the wand into itself?

2023-05-13 07:03 UTC, OneEyeMaker commented
There is keyboard shortcut which allows to move any item to hotbar (IDK, is one added by vanilla or by tweaks mods).
Using this shortcut with current implementation allows move item away and destroy it.

Steps to reproduce:
1) Place ore finder on hotbar in ***N***-th slot.
2) Open it's UI.
3) Hover mouse over any empty slot.
4) Press Ctrl+***N*** (index of slot where ore finder is located, Ctrl+3, for example).
Result: item is moved from original slot.
5) Drag and drop item away from UI window.
Item is destroyed.

2023-05-13 07:17 UTC, OneEyeMaker commented
After few more tests I found that item is destroyed only when NEI is enabled. But anyway I think that moving item from "locked" position isn't a desired behavior.

2023-05-13 11:24 UTC, wlhlm commented
This actually vanilla functionality. `net.minecraft.client.gui.inventory.GuiContainer#checkHotbarKeys`

2023-05-13 12:36 UTC, wlhlm commented
OK, I have reworked the locked slot handling more akin to what Forestry does. This was very enlightening. Please have a look.

I'm gonna have to fix the GT++ backpack next (though probably nobody uses them 😛)

2023-05-13 14:06 UTC, OneEyeMaker requested changes
Very good job!

Add just one method override to slot class for safety.

2023-05-13 14:06 UTC, OneEyeMaker commented on src/main/java/com/encraft/dz/container/SlotBlockedItemInv.java
> +
```suggestion

    @Override
    public void putStack(ItemStack itemStack) {}

```

2023-05-13 14:11 UTC, wlhlm commented
Committed (also updated the GT++ PR). Thank you.

2023-05-13 14:14 UTC, OneEyeMaker approved these changes

2023-05-13 15:37 UTC, merged